version: '3.3'
services:
  mysql:
    platform: linux/x86_64 # M1 mac用に追加
    image: mysql:5.7 #MySQLのバージョンを指定
    container_name: db-for-go

    # MySQLの設定値を指定
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --sql-mode=ONLY_FULL_GROUP_BY,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION

    # コンテナ内で使用する環境変数の値を指定
    environment:
      MYSQL_ROOT_USER: ${ROOTUSER}
      MYSQL_ROOT_PASSWORD: ${ROOTPASS}
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${USERNAME}
      MYSQL_PASSWORD: ${USERPASS}
      TZ: 'Asia/Tokyo'

    # コンテナの3306番ポートを、ローカルの3306番ポートに繋げる
    ports:
      - '3306:3306'

    # コンテナ内にあるMySQLに格納するデータを永続化させるために使用するボリュームを指定
    volumes:
      - db-volume:/var/lib/mysql

# ボリュームの作成
volumes:
  db-volume:
